apiVersion: apps/v1 
kind: Deployment
metadata:
  name: some-deployment
  labels: 
    typ: deploy
spec:
  selector:
    matchLabels:
      project: some-deployment
  template: 
    metadata:
      labels: 
        project: some-deployment
    spec: 
      containers:
      - name: some-container
        image: apache:latest
        resources:
          limits:
            cpu: "1"  
            memory: "128M"
          requests:
            cpu: "0.1"
            memory: "128M"
        readinessProbe:
          httpGet:
            path: / 
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: some-hpa
  labels: 
    typ: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: some-deployment
  minReplicas: 1
  maxReplicas: 4
  metrics: 
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: some-pdb
  labels: 
    typ: pbd
spec:
  minAvailable: 2
  selector:
    matchLabels:
      project: some-deployment